#!/bin/sh
host=`/bin/hostname -s`
bupdir="/mnt/dietpi-backup"
indir="${bupdir}/dietpi-backup_system"
outdir="/mnt/samba/backups"
/bin/echo -e "1\n1\n0\n0\n1" > /DietPi/dietpi/.dietpi-cleaner
/DietPi/dietpi/dietpi-cleaner 1 > /dev/null 2>&1 || exit 1
/bin/echo -e "FP_TARGET_BACKUP=${bupdir}\nBACKUP_MODE=0" > /DietPi/dietpi/.dietpi-backup_settings
/DietPi/dietpi/dietpi-backup 1 "$bupdir" > /dev/null || exit 1
/bin/mountpoint /mnt/samba > /dev/null || exit 1
last=`/usr/bin/find "$outdir" -path "${outdir}/*/*" -prune -o -type f -regextype posix-extended -regex "^${outdir}/${host}_[0-9]{10}_(FULL|DIFF).[0-9]?.dar$" -printf "%C@ %p\n" | /usr/bin/sort -n | /usr/bin/awk -F'[. ]' '{print $3}' | /usr/bin/tail -n1`
now=`/bin/date +%s`
if [ `/bin/date +%d` -eq 01 -o "$1" = "full" -o "$last" = "" ]; then
    file="${outdir}/${host}_${now}_FULL"
    /usr/bin/dar -q -Q -m 256 -zgzip:7 -Z compress-exclusion -R "$indir" -ar -D -P "var\/[^w]{3}.*" -c "$file" || exit 1
    /usr/bin/find "$outdir" -path "${outdir}/*/*" -prune -o -type f -regextype posix-extended -regex "^${outdir}/${host}_[0-9]{10}_(FULL|DIFF).[0-9]?.dar$" -mtime +60 -print -exec rm {} \;
else
    file="${outdir}/${host}_${now}_DIFF"
    /usr/bin/dar -q -Q -m 256 -zgzip:7 -Z compress-exclusion -R "$indir" -ar -D -P "var\/[^w]{3}.*" -c "$file" -A "$last" || exit 1
fi
/usr/bin/dar -q -Q -t "$file" > /dev/null || exit 1
/bin/echo "Backup successful: `/bin/ls -hl ${file}* | /usr/bin/awk '{print $5}'` `/usr/bin/basename ${file}*`"
exit 0
