#!/bin/sh
host=`/bin/hostname -s`
pidir="/mnt/dietpi-backup"
outdir="/mnt/samba"
indir="${pidir}/dietpi-backup_system"
last=`/usr/bin/find "$outdir" -path "${outdir}/*/*" -prune -o -type f -regextype posix-extended -regex "^${outdir}/${host}_[0-9]{10}_SYSBUP-(FULL|DIFF).[0-9]?.dar$" -printf "%C@ %p\n" | sort -n | awk -F'[. ]' '{print $3}' | tail -n1`
/DietPi/dietpi/dietpi-backup 1 "$pidir" > /dev/null 2>&1 || { /bin/echo "dietpi-backup error!"; exit 1; }
/bin/mountpoint -q "$outdir" || { /bin/echo "share not mounted!"; exit 1; }
secs=`/bin/date +%s`
file="${outdir}/${host}_${secs}_SYSBUP-DIFF"
/usr/bin/dar -m 256 -zgzip:7 -Z compress-exclusion -R "$indir" -c "$file" -A "$last" || { /bin/echo "dar failed!"; exit 1; }
/usr/bin/dar -t "$file" > /dev/null 2>&1 || { /bin/echo "dar verification failed!"; exit 1; }
/bin/echo "daily differential backup successful"; exit 0
